- hosts: localhost
  vars:
    application_project: sock-shop
    istio_project: sockshop-istio-system
    base_domain: cluster-bd7c.bd7c.sandbox936.opentlc.com
  tasks:
  #- name: Create cert.cfg
  #  template:
  #    src: templates/cert.cfg.j2
  #    dest: tmp/cert.cfg
  #- name: Generate openssl certificate and key
  #  command: "openssl req -x509 -config tmp/cert.cfg -extensions req_ext -nodes -days 730 -newkey rsa:2048 -sha256 -keyout tmp/tls.key -out tmp/tls.crt"
  #- name: Create tls secret to openshift cluster
  #  command: "oc create secret tls istio-ingressgateway-certs --cert tmp/tls.crt --key tmp/tls.key -n {{ istio_project }}"
  #- name: Add annotations to deployments
  #  k8s:
  #    state: present
  #    namespace: "{{ istio_project }}"
  #    merge_type: merge
  #    definition:
  #      apiversion: apps/v1
  #      kind: Deployment
  #      metadata:
  #        name: istio-ingressgateway
  #      spec:
  #        template:
  #          metadata:
  #            annotations:
  #              kubectl.kubernetes.io/restartedAt: "{{ansible_date_time.iso8601}}"
  #- name: Create gateway 
  #  k8s:
  #    state: present
  #    namespace: "{{ application_project }}"
  #    src: manifests/wildcard-gateway.yaml
  - name: Fetch all services in bookinfo namespace
    set_fact:
      services: "{{ lookup('k8s', kind='Service', namespace='sock-shop') }}"
    register: services
  - name: Create policies for enabling mtls
    k8s:
      state: present
      namespace: "{{ application_project }}"
      definition:
        apiVersion: authentication.istio.io/v1alpha1
        kind: Policy
        metadata:
          name: "{{ item.metadata.name }}-mtls"
        spec:
          peers:
          - mtls:
              mode: PERMISSIVE
          targets:
          - name: "{{ item.metadata.name }}"
    loop: "{{ services }}"
  - name: Create destinationrules
    k8s:
      state: present
      namespace: "{{ application_project }}"
      definition:
        apiVersion: networking.istio.io/v1alpha3
        kind: DestinationRule
        metadata:
          name: "{{ item.metadata.name }}-mtls"
        spec:
          host: "{{ item.metadata.name }}.{{ application_project }}.svc.cluster.local"
          trafficPolicy:
            tls:
              mode: ISTIO_MUTUAL
    loop: "{{ services }}"
  #- name: Create virtualservice
  #  k8s:
  #    state: present
  #    namespace: "{{ application_project }}"
  #    definition:
  #      apiVersion: networking.istio.io/v1alpha3
  #      kind: VirtualService
  #      metadata:
  #        name: product-page-virtualservice
  #      spec:
  #        hosts:
  #          - productpage.{{ application_project }}.apps.{{ base_domain }}
  #        gateways:
  #          - bookinfo-wildcard-gateway
  #        http:
  #        - match:
  #          - uri:
  #              prefix: /
  #          route:
  #          - destination:
  #              port:
  #                number: 9080
  #              host: productpage.bookinfo.svc.cluster.local
  #- name: Create http route for productpage
  #  k8s:
  #    state: present
  #    namespace: "{{ istio_project }}"
  #    definition:
  #      apiVersion: route.openshift.io/v1
  #      kind: Route
  #      metadata:
  #        annotations:
  #          openshift.io/host.generated: "true"
  #        labels:
  #          app: productpage-service
  #        name: productpage-service-gateway-http
  #      spec:
  #        host: productpage.{{ application_project }}.apps.{{ base_domain }}
  #        port:
  #          targetPort: https
  #        tls:
  #          termination: passthrough
  #        to:
  #          kind: Service
  #          name: istio-ingressgateway
  #          weight: 100
  #        wildcardPolicy: None
